#pragma once

//Moi
#ifndef CBMu_ENABLE_RENDER_DIAGNOSTICS
#define CBMu_ENABLE_RENDER_DIAGNOSTICS 0
#endif

// GPU Compute Offloading
#ifndef CBMu_ENABLE_GPU_COMPUTE
#define CBMu_ENABLE_GPU_COMPUTE 1
#endif

#ifndef CBMu_ENABLE_GPU_WATER_COMPUTE
#define CBMu_ENABLE_GPU_WATER_COMPUTE CBMu_ENABLE_GPU_COMPUTE
#endif

#ifndef CBMu_ENABLE_GPU_DYNAMIC_LIGHTING
#define CBMu_ENABLE_GPU_DYNAMIC_LIGHTING 1
#endif

#ifndef CBMu_ENABLE_GPU_CLOTH_COMPUTE
#define CBMu_ENABLE_GPU_CLOTH_COMPUTE 0 // Disabled: critical architectural bugs (see review)
#endif

//Moi
#ifndef CBMu_ENABLE_CPU_HOTSPOT_PROFILER
#define CBMu_ENABLE_CPU_HOTSPOT_PROFILER 0
#endif

//Moi
#ifndef CBMu_ENABLE_GL_DEBUG_COUNTERS
#define CBMu_ENABLE_GL_DEBUG_COUNTERS CBMu_ENABLE_RENDER_DIAGNOSTICS
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_SPLIT_TOPN_MODEL_FILE
#define CBMu_ENABLE_GL_BMD_SPLIT_TOPN_MODEL_FILE CBMu_ENABLE_RENDER_DIAGNOSTICS
#endif

//Moi
#ifndef CBMu_ENABLE_CHARACTER_VISUAL_SUBSCOPE_DETAIL
#define CBMu_ENABLE_CHARACTER_VISUAL_SUBSCOPE_DETAIL 1
#endif

//Moi
#ifndef CBMu_ENABLE_BODYMESH_DETAIL_COUNTERS
#define CBMu_ENABLE_BODYMESH_DETAIL_COUNTERS CBMu_ENABLE_RENDER_DIAGNOSTICS
#endif




#ifndef CBMu_ENABLE_GL_STATE_CACHE
#define CBMu_ENABLE_GL_STATE_CACHE 1
#endif



#ifndef CBMu_ENABLE_GL_BMD_WEARABLE_COMPOSITE
#define CBMu_ENABLE_GL_BMD_WEARABLE_COMPOSITE 0
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_WEARABLE_COMPOSITE_BODY_ARMOR
#define CBMu_ENABLE_GL_BMD_WEARABLE_COMPOSITE_BODY_ARMOR 0
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_BONE_SNAPSHOT_POINTER_CACHE
#define CBMu_ENABLE_GL_BMD_BONE_SNAPSHOT_POINTER_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_EQUIPMENT_DIRECT_EMITTER
#define CBMu_ENABLE_GL_EQUIPMENT_DIRECT_EMITTER 1
#endif



#ifndef CBMu_ENABLE_PARTICLE_POOL_CURSOR
#define CBMu_ENABLE_PARTICLE_POOL_CURSOR 1
#endif


#ifndef CBMu_ENABLE_PARTICLE_ACTIVE_RANGE
#define CBMu_ENABLE_PARTICLE_ACTIVE_RANGE 1
#endif


#ifndef CBMu_ENABLE_PARTICLE_LIVE_RENDER_LIST
#define CBMu_ENABLE_PARTICLE_LIVE_RENDER_LIST 1
#endif



#ifndef CBMu_ENABLE_JOINT_POOL_CURSOR
#define CBMu_ENABLE_JOINT_POOL_CURSOR 1
#endif


#ifndef CBMu_ENABLE_JOINT_ACTIVE_RANGE
#define CBMu_ENABLE_JOINT_ACTIVE_RANGE 1
#endif


#ifndef CBMu_ENABLE_GL_JOINT_SCRATCH_REUSE
#define CBMu_ENABLE_GL_JOINT_SCRATCH_REUSE 1
#endif


#ifndef CBMu_ENABLE_GL_JOINT_CPU_COLOR_CACHE
#define CBMu_ENABLE_GL_JOINT_CPU_COLOR_CACHE 1
#endif



#ifndef CBMu_ENABLE_GL_BMD_COMMAND_SORT
#define CBMu_ENABLE_GL_BMD_COMMAND_SORT 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_INSTANCED_SORT_KEY
#define CBMu_ENABLE_GL_BMD_INSTANCED_SORT_KEY 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_SORT_KEY_CACHE
#define CBMu_ENABLE_GL_BMD_SORT_KEY_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_UBO_CACHE
#define CBMu_ENABLE_GL_BMD_UBO_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_UBO_BIND_CACHE
#define CBMu_ENABLE_GL_BMD_UBO_BIND_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_UBO_RING
#define CBMu_ENABLE_GL_BMD_UBO_RING 1
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_UBO_RING_ORPHAN
#define CBMu_ENABLE_GL_BMD_UBO_RING_ORPHAN 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_UBO_UPDATE_SKIP
#define CBMu_ENABLE_GL_BMD_UBO_UPDATE_SKIP 0
#endif


#ifndef CBMu_ENABLE_GL_BMD_VAO_BIND_CACHE
#define CBMu_ENABLE_GL_BMD_VAO_BIND_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_SHADER_SCOPE_CACHE
#define CBMu_ENABLE_GL_BMD_SHADER_SCOPE_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_MATRIX_CACHE
#define CBMu_ENABLE_GL_BMD_MATRIX_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_DEFER_LAZY_MATRIX_SNAPSHOT
#define CBMu_ENABLE_GL_BMD_DEFER_LAZY_MATRIX_SNAPSHOT 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_SKIP_EMPTY_FLUSH
#define CBMu_ENABLE_GL_BMD_SKIP_EMPTY_FLUSH 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_DEFER_CHARACTER_FLUSH
#define CBMu_ENABLE_GL_BMD_DEFER_CHARACTER_FLUSH 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_OBJECT_DEFER
#define CBMu_ENABLE_GL_BMD_OBJECT_DEFER 1
#endif




#ifndef CBMu_ENABLE_GL_BMD_BONE_UNIFORM_CACHE
#define CBMu_ENABLE_GL_BMD_BONE_UNIFORM_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_BONE_PACK_SCRATCH_REUSE
#define CBMu_ENABLE_GL_BMD_BONE_PACK_SCRATCH_REUSE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_PACKED_BONE_CACHE
#define CBMu_ENABLE_GL_BMD_PACKED_BONE_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_CACHE_VALUE_STORAGE
#define CBMu_ENABLE_GL_BMD_CACHE_VALUE_STORAGE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_TRANSFORMED_BONE_ROW_CACHE
#define CBMu_ENABLE_GL_BMD_TRANSFORMED_BONE_ROW_CACHE 1
#endif





#ifndef CBMu_ENABLE_GL_BMD_COMMAND_POOL_REUSE
#define CBMu_ENABLE_GL_BMD_COMMAND_POOL_REUSE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_GLOBAL_CHARACTER_DEFER
#define CBMu_ENABLE_GL_BMD_GLOBAL_CHARACTER_DEFER 1
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_GOLDEN_OVERLAY_SEMANTIC
#define CBMu_ENABLE_GL_BMD_GOLDEN_OVERLAY_SEMANTIC 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_SKINNED_INSTANCED_BATCH
#define CBMu_ENABLE_GL_BMD_SKINNED_INSTANCED_BATCH 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_ADDITIVE_INSTANCED_BATCH
#define CBMu_ENABLE_GL_BMD_ADDITIVE_INSTANCED_BATCH 1
#endif

#ifndef CBMu_ENABLE_GL_BMD_CHROME_BRIGHT_INSTANCED_BATCH
#define CBMu_ENABLE_GL_BMD_CHROME_BRIGHT_INSTANCED_BATCH 1
#endif

#ifndef CBMu_USE_VULKAN_NATIVE_MESH
#define CBMu_USE_VULKAN_NATIVE_MESH 1
#endif

#ifndef CBMu_ENABLE_VK_INDIRECT_DRAW
#define CBMu_ENABLE_VK_INDIRECT_DRAW 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_INSTANCE_PARAM_KEY_RELAX
#define CBMu_ENABLE_GL_BMD_INSTANCE_PARAM_KEY_RELAX 1
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_INSTANCE_COMPOSITE_COLOR
#define CBMu_ENABLE_GL_BMD_INSTANCE_COMPOSITE_COLOR 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_BONE_TEXTURE_BUFFER
#define CBMu_ENABLE_GL_BMD_BONE_TEXTURE_BUFFER 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_TBO_NON_INSTANCED
#define CBMu_ENABLE_GL_BMD_TBO_NON_INSTANCED 1
#endif



#ifndef CBMu_ENABLE_GL_BMD_SPLIT_COUNTERS
#define CBMu_ENABLE_GL_BMD_SPLIT_COUNTERS 1
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_SPLIT_TOPN_DIAGNOSTICS
#define CBMu_ENABLE_GL_BMD_SPLIT_TOPN_DIAGNOSTICS 0
#endif


#ifndef CBMu_ENABLE_GL_BMD_SPLIT_TOPN_PACKED_BONE_ONLY
#define CBMu_ENABLE_GL_BMD_SPLIT_TOPN_PACKED_BONE_ONLY 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_CHROME_BRIGHT_INSTANCED_BATCH
#define CBMu_ENABLE_GL_BMD_CHROME_BRIGHT_INSTANCED_BATCH 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_TBO_STATE_CACHE
#define CBMu_ENABLE_GL_BMD_TBO_STATE_CACHE 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_BONE_TBO_RING
#define CBMu_ENABLE_GL_BMD_BONE_TBO_RING 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_FAST_BONE_ROW_UPLOAD_PACK
#define CBMu_ENABLE_GL_BMD_FAST_BONE_ROW_UPLOAD_PACK 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_INSTANCE_VBO_RING
#define CBMu_ENABLE_GL_BMD_INSTANCE_VBO_RING 1
#endif


#ifndef CBMu_ENABLE_GL_BMD_TBO_EXTENDED_BONE_ROWS
#define CBMu_ENABLE_GL_BMD_TBO_EXTENDED_BONE_ROWS 1
#endif


#ifndef CBMu_GL_BMD_BONE_TEXTURE_BUFFER_MAX_ROWS
#define CBMu_GL_BMD_BONE_TEXTURE_BUFFER_MAX_ROWS 65536
#endif




#ifndef CBMu_ENABLE_EFFECT_POOL_CURSOR
#define CBMu_ENABLE_EFFECT_POOL_CURSOR 1
#endif


#ifndef CBMu_ENABLE_EFFECT_ACTIVE_RANGE
#define CBMu_ENABLE_EFFECT_ACTIVE_RANGE 1
#endif


#ifndef CBMu_ENABLE_EFFECT_RANGE_SQRT_SKIP
#define CBMu_ENABLE_EFFECT_RANGE_SQRT_SKIP 1
#endif


#ifndef CBMu_ENABLE_WORLD_DISTANCE_SQRT_SKIP
#define CBMu_ENABLE_WORLD_DISTANCE_SQRT_SKIP 1
#endif


#ifndef CBMu_ENABLE_OBJECT_FORCE_RENDER_CONTEXT_CACHE
#define CBMu_ENABLE_OBJECT_FORCE_RENDER_CONTEXT_CACHE 1
#endif


#ifndef CBMu_ENABLE_CHARACTER_ACTIVE_RANGE
#define CBMu_ENABLE_CHARACTER_ACTIVE_RANGE 1
#endif


#ifndef CBMu_ENABLE_CHARACTER_TERRAIN_DIRTY_CLEAR
#define CBMu_ENABLE_CHARACTER_TERRAIN_DIRTY_CLEAR 1
#endif


#ifndef CBMu_ENABLE_CHARACTER_EQUIP_DECORATION_BUDGET
#define CBMu_ENABLE_CHARACTER_EQUIP_DECORATION_BUDGET 0
#endif

//Moi
#ifndef CBMu_CHARACTER_EQUIP_DECORATION_MAX_DISTANCE
#define CBMu_CHARACTER_EQUIP_DECORATION_MAX_DISTANCE 3500.0f
#endif

//Moi
#ifndef CBMu_CHARACTER_EQUIP_LINKED_MODEL_MAX_DISTANCE
#define CBMu_CHARACTER_EQUIP_LINKED_MODEL_MAX_DISTANCE 3500.0f
#endif


#ifndef CBMu_ENABLE_CUSTOM_MONSTER_GLOW_LOOKUP_CACHE
#define CBMu_ENABLE_CUSTOM_MONSTER_GLOW_LOOKUP_CACHE 1
#endif

//Moi
#ifndef CBMu_ENABLE_CHARACTER_VISUAL_GOLDEN_CACHE
#define CBMu_ENABLE_CHARACTER_VISUAL_GOLDEN_CACHE 1
#endif

//Moi
#ifndef CBMu_ENABLE_CHARACTER_VISUAL_MAP_CONTEXT_CACHE
#define CBMu_ENABLE_CHARACTER_VISUAL_MAP_CONTEXT_CACHE 1
#endif

//Moi
#ifndef CBMu_ENABLE_CHARACTER_VISUAL_SKIP_MAP_MONSTER_CHAIN
#define CBMu_ENABLE_CHARACTER_VISUAL_SKIP_MAP_MONSTER_CHAIN 1
#endif

//Moi
#ifndef CBMu_ENABLE_CHARACTER_VISUAL_SKIP_EMPTY_BUFF_FX
#define CBMu_ENABLE_CHARACTER_VISUAL_SKIP_EMPTY_BUFF_FX 1
#endif

//Moi
#ifndef CBMu_ENABLE_CHARACTER_VISUAL_FULLSET_CACHE
#define CBMu_ENABLE_CHARACTER_VISUAL_FULLSET_CACHE 0
#endif

//Moi
#ifndef CBMu_ENABLE_GL_BMD_SHADER_TRANSFORM_SKIP_CPU_SKIN
#define CBMu_ENABLE_GL_BMD_SHADER_TRANSFORM_SKIP_CPU_SKIN 1
#endif


#ifndef CBMu_ENABLE_SPRITE_POOL_CURSOR
#define CBMu_ENABLE_SPRITE_POOL_CURSOR 1
#endif


#ifndef CBMu_ENABLE_SPRITE_ACTIVE_RANGE
#define CBMu_ENABLE_SPRITE_ACTIVE_RANGE 1
#endif


#ifndef CBMu_ENABLE_SPRITE_LIVE_RENDER_LIST
#define CBMu_ENABLE_SPRITE_LIVE_RENDER_LIST 1
#endif


#ifndef CBMu_ENABLE_EFFECT_BONE_SCRATCH_REUSE
#define CBMu_ENABLE_EFFECT_BONE_SCRATCH_REUSE 1
#endif


#ifndef CBMu_ENABLE_PHYSICS_CLOTH_RENDER_SCRATCH_REUSE
#define CBMu_ENABLE_PHYSICS_CLOTH_RENDER_SCRATCH_REUSE 1
#endif
